# Generated by Django 5.0.1 on 2026-02-12 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0012_lawenforcementaccount_policestation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lawenforcementaccount',
            name='type',
            field=models.CharField(default='law_enforcement', max_length=5),
        ),
    ]
