# Generated by Django 5.0.1 on 2026-02-20 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0013_alter_lawenforcementaccount_type'),
        ('account', '0016_rename_type_twilio_account_type'),
    ]

    operations = [
    ]
