# Generated by Django 5.0.1 on 2026-02-24 10:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0017_merge_20260220_1537'),
    ]

    operations = [
        migrations.CreateModel(
            name='HealthcareAccount',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('first_name', models.CharField(max_length=100)),
                ('middle_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=100)),
                ('status', models.CharField(blank=True, default='Active', max_length=100, null=True)),
                ('region', models.CharField(blank=True, max_length=100, null=True)),
                ('province', models.CharField(blank=True, max_length=100, null=True)),
                ('hospital_name', models.CharField(blank=True, max_length=100, null=True)),
                ('type', models.CharField(default='healthcare', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='SWDOaccount',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('name', models.CharField(max_length=100)),
                ('status', models.CharField(blank=True, default='Active', max_length=100, null=True)),
                ('type', models.CharField(default='SWDO', max_length=20)),
                ('region', models.CharField(blank=True, max_length=100, null=True)),
                ('province', models.CharField(blank=True, max_length=100, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='twilio',
            name='type',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='lawenforcementaccount',
            name='type',
            field=models.CharField(default='law_enforcement', max_length=15),
        ),
    ]
