# Generated by Django 5.0.1 on 2026-02-24 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0018_healthcareaccount_swdoaccount_twilio_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lawenforcementaccount',
            name='city',
        ),
    ]
