# Generated by Django 5.0.1 on 2026-02-24 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0019_remove_lawenforcementaccount_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='lawenforcementaccount',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
