# Generated by Django 5.0.1 on 2026-02-24 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0020_lawenforcementaccount_city'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lawenforcementaccount',
            old_name='barangay',
            new_name='station',
        ),
        migrations.RemoveField(
            model_name='lawenforcementaccount',
            name='city',
        ),
        migrations.AlterField(
            model_name='lawenforcementaccount',
            name='type',
            field=models.CharField(default='law_enforcement', max_length=20),
        ),
    ]
