# Generated by Django 5.0.1 on 2026-02-20 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case', '0016_delete_lawenforcementreferredcase'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='SWDO_other',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='case',
            name='healthcare_other',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='case',
            name='law_enforcement_others',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='case',
            name='refer_to_barangay_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='case',
            name='refer_to_barangay_from_healthcare_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='case',
            name='refer_to_barangay_from_social_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='case',
            name='refers_to_barangay_from_SWDO',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='case',
            name='remark_to_barangay_from_SWDO',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='case',
            name='remarks_to_barangay',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='case',
            name='remarks_to_barangay_from_healthcare',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='case',
            name='remarks_to_healthcare',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='case',
            name='remarks_to_law_enforcement',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='case',
            name='remarks_to_social_welfare',
            field=models.TextField(blank=True, null=True),
        ),
    ]
